default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: jcottobboni
  password: "abissal"
  host: localhost

development:
  <<: *default
  database: helping

test:
  <<: *default
  database: helping_test

production:
  <<: *default
  database: helping_prod
